//
// Mactive Slide Show for Ipix Photos
// Author: G. LaPinsky
// Date:   January 15, 2004
//
// NOTES:
//   This is an adaptation of an iPIX slide show to work in conjuction with the Mactive 
//   Ipix tag with dataType = "WebPhotoSlideShow".
//   The script cycles through the ipix images submitted for an online ad and displays
//   them slide show style.
//
//   If you change this code make sure it still works with the Ipix tag.
//
// REQUIREMENTS:
//   initslideshow() must be called first to init the URLs of the ipix images that
//   are to be included in the slide show. Note that the slide <img> generated by the
//   custom tag is pre-loaded with the first image, i.e. rimfireURL[0] so if there are
//   at least two images, we set curpicture to 1 so the second image, i.e. rimfirURL[1]
//   gets displayed next. In the case of the Ipix tag, the script generated by the tag
//   calls initslideshow().
//
//   slidetimedelay() must be called once to kick off the slide timer.
//
// CAVEATS:
//   In order for the script to not degenerate there must at least one URL in the list
//   passed to initslideshow().
//
// DESCRIPTION:
//

var rimfireURL = null;
var curpicture=0;
var play = 1;

function initslideshow(urls)
{
    //alert("photo urls: " + urls);
    if (rimfireURL == null) {
        rimfireURL = urls;
	if (rimfireURL.length > 1){
	    curpicture=1;
	}
    }
}

function slideshowupdate(imgName,controls)
{
    if (play == 1){
        slidesslideshow = new Image(37,149);
        slidesslideshow.src = rimfireURL[curpicture];
        slideshow = eval(imgName + "slideshow.src");
        document[imgName].src = slideshow;
        curpicture=curpicture + 1;
        if (curpicture >= rimfireURL.length){
            curpicture=0;
        }
        if (controls != 1){
            slidetimedelay();
        }
        return;
    }
    slidetimedelay();
    return;
}

function slidetimedelay()
{
    var timerID = setTimeout("slideshowupdate('slides',0)",5000);
}

function cplay(){
    play=1;
}

function cbegin(){
    if (play == 0){
        play=1;
        curpicture=0;
        slideshowupdate('slides');
        play=0;
        return;
    }
    curpicture=0;
    slideshowupdate('slides',1);
}

function cprev()
{
    // curpicture always points to the NEXT picture not the one displayed so we must
    //   back up twice to get to previous image and handle wrapping in the process...
    curpicture = ((curpicture + rimfireURL.length) - 1) % rimfireURL.length;
    curpicture = ((curpicture + rimfireURL.length) - 1) % rimfireURL.length;

    if (play == 0){
        play=1;
        slideshowupdate('slides',1);
        play=0;
        return;

    }

    slideshowupdate('slides',1);
}

function cnext(){
    if (play == 0){
        play=1;
        slideshowupdate('slides',1);
        play=0;
        return;
    }
    slideshowupdate('slides',1);
}

function cstop(){
    play=0;
}
